# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=dirk
    - DISABLE_TESTS=true

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu NAME=linux-x86_64-gnu
    - env: TARGET=x86_64-unknown-linux-musl NAME=linux-x86_64-musl
    - env: TARGET=i686-unknown-linux-gnu NAME=linux-i686-gnu
    - env: TARGET=i686-unknown-linux-musl NAME=linux-i686-musl
    - env: TARGET=aarch64-unknown-linux-gnu NAME=linux-aarch64-gnu
    - env: TARGET=arm-unknown-linux-gnueabi NAME=linux-arm-gnueabi

    # OSX
    - env: TARGET=i686-apple-darwin NAME=apple-i686-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin NAME=apple-x86_64-darwin
      os: osx

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu NAME=linux-x86_64-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin NAME=apple-x86_64-darwin
      os: osx
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "RhxuyO72rg9zwxTxNo80QkZu001SD7R6B6EzICl99eCIavXto65zpl+tY6cqFvB9v/e3i7Z59ZVX0IiAxov3MNC75/41unejwEJDutvF0uzX6QfosTJb35T4fcoAJKOgmzAxLGImspErBL7wPoi8VT3+4gSVdZ+9gr3PUL8zK4/gNDIB9CeXNMSVyv5F8kPWYA84H/C02Oj5auc0DGokdBIwxFMqkCbYICi+WyRyr18XzucRfa+NQ/4h1IUOplRADqzubm5pQMFvNNGSJkpKKmBRZkrDqehoa0WB3BOjRujgo2twIMftXZefG+OSyEI8meBvlozveCWRK3lDtEI8P0cQyCwMrZQ4cloZo+I+xOhFFdpue/MEFTPUpKtGZwK9xOWhiP/X4Do/3TgPB0tMo6K9vEmwizxvy/bHnD4XFaI4+NPkkEQllQYh9a5kvc/VvVg6EEj12Y3DcywyoxTLedsv15hJIy4wEYdMoA6632hCMA2KVFfZ+NU4bVrdfYdl09GgQGJOvHm5jj0Jf140DbN4TFYB2TTdL3xNXrK5z4J2YUp/F54u0ANLblNN9zUy1UXtT9ryayJrUI282tZZ3ei9qSIuHtWjSAAq+M+TEvBPe5/D2/Ue6+KvjYMMHI/qaLU2qDa3qHjHA6fbskpHpprmKgzEx3eARDoLyV/jJ3E="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$NAME.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never